DIM = N N N

NAC = .TRUE.

PRIMITIVE_AXES = AUTO

MASS = Mass1 Mass2 ...

BAND = qx1 qy1 qz1 qx2 qy2 qz2 ... ... ...
BAND_POINTS = 101
BAND_LABELS = $\Gamma$ ... ...
BAND_CONNECTION = .TRUE.
BAND_FORMAT = YAML

MESH = Q1 Q2 Q3
GAMMA_CENTER = .TRUE.

WRITE_MESH = .TRUE.
MESH_FORMAT = YAML

DOS = .TRUE.

EIGENVECTORS = .TRUE.
